#!/usr/bin/env python3
"""
Interactive setup wizard for Telegram Media Downloader
Guides user through configuration on first run
"""

import os
import sys
import subprocess
from pathlib import Path


def install_dependencies():
    """Install required packages"""
    print("\n[*] Installing dependencies...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"])
        print("[+] Dependencies installed\n")
        return True
    except Exception as e:
        print(f"[-] Installation error: {e}")
        return False


def get_credentials():
    """Interactive credentials input"""
    print("\n" + "="*60)
    print("SETUP API CREDENTIALS")
    print("="*60)
    print("\n1. Go to https://my.telegram.org")
    print("2. Create an application")
    print("3. Copy API ID and API Hash\n")

    print("Enter your credentials (or press Enter to skip):\n")

    api_id = input("API ID: ").strip()
    if not api_id:
        print("[-] API ID is required!")
        return None

    api_hash = input("API Hash: ").strip()
    if not api_hash:
        print("[-] API Hash is required!")
        return None

    phone = input("Phone number (+79991234567): ").strip()
    if not phone:
        print("[-] Phone number is required!")
        return None

    return {
        'api_id': api_id,
        'api_hash': api_hash,
        'phone': phone
    }


def save_env(credentials):
    """Save credentials to .env file"""
    env_content = f"""# Telegram API Credentials
# Auto-generated by setup wizard

TELEGRAM_API_ID={credentials['api_id']}
TELEGRAM_API_HASH={credentials['api_hash']}
TELEGRAM_PHONE={credentials['phone']}
"""

    with open('.env', 'w') as f:
        f.write(env_content)

    print("\n[+] Settings saved to .env\n")


def check_and_load_env():
    """Check if .env exists and load it"""
    if os.path.exists('.env'):
        print("[+] Found saved settings\n")
        # Load .env
        from dotenv import load_dotenv
        load_dotenv()
        return True
    return False


def main():
    print("\n")
    print("=" * 60)
    print("TELEGRAM MEDIA DOWNLOADER - SETUP WIZARD".center(60))
    print("=" * 60)

    # Step 1: Check Python version
    if sys.version_info < (3, 7):
        print("[-] Python 3.7+ is required")
        sys.exit(1)

    # Step 2: Install dependencies
    if not install_dependencies():
        sys.exit(1)

    # Step 3: Check credentials
    if not check_and_load_env():
        print("[*] First run - setup required\n")
        credentials = get_credentials()
        if not credentials:
            print("[-] Cancelled by user")
            sys.exit(1)
        save_env(credentials)

    # Step 4: Check env vars
    api_id = os.getenv('TELEGRAM_API_ID')
    api_hash = os.getenv('TELEGRAM_API_HASH')
    phone = os.getenv('TELEGRAM_PHONE')

    if not all([api_id, api_hash, phone]):
        print("[-] Environment variables not set!")
        sys.exit(1)

    print("="*60)
    print("[+] READY TO START!")
    print("="*60)
    print(f"\n[*] Account: {phone}")
    print(f"[*] API ID: {api_id[:4]}...{api_id[-4:]}" if len(api_id) > 8 else f"[*] API ID: {api_id}")
    print("\n[*] Starting Telegram Media Downloader...\n")

    # Step 5: Run main script
    os.execvp(sys.executable, [sys.executable, 'telegram_media_downloader.py'])


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n[-] Cancelled by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n[-] Error: {e}")
        sys.exit(1)
